"""empty message

Revision ID: 89212eccaca2
Revises: 176dd61f0846
Create Date: 2020-10-26 13:47:12.700272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89212eccaca2'
down_revision = '176dd61f0846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('release_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('actor_movie',
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('actor_id', 'movie_id')
    )
    op.add_column('actors', sa.Column('date_of_birth', sa.DateTime(), nullable=False))
    op.drop_column('actors', 'age')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('actors', 'date_of_birth')
    op.drop_table('actor_movie')
    op.drop_table('movies')
    # ### end Alembic commands ###
